name: Flutter CI

on:
  push:
    branches:
      - main
      - development
      - 'fix/**'
      - 'refactor/**'
      - 'feature/**'
  pull_request:
    branches:
      - main
      - development

jobs:
  analyze-and-test:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.0
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --reporter expanded
